### ISSUE TITLE
BUG: Theme not responsive

### ISSUE THREAD

**Issue by Jonasdero** [pacollins/hugo-future-imperfect-slim#18] opened 2019-06-09 17:16 UTC
# Bug Report
## Describe the bug
Especially on smaller mobile screens you first have to zoom out before you can see the full webpage. I removed all of my custom css and its still too big. 

Also when changing the font-size, the text-boxes stay the same size relative to the text.

## To Reproduce
1. Open Site with theme on mobile

## Expected behavior
Correct site size

##Screenshots
![image](https://user-images.githubusercontent.com/11200310/59162055-e1fdd580-8aea-11e9-8a89-b67a25797b75.png)

## Environment
 - **Hugo Version:** v0.55.6
 - **Browser and Version:**  Chrome 75.0.3770.80
 - **Platform:** Desktop/Mobile
 - **Link to Project: Private**

**Comment by pacollins** [comment] 2019-06-09 19:00
Can you check [my site](https://www.pacollins.com/)? I don't have this issue on my S10e.

Or can you link to a live version of your site?

**Comment by Jonasdero** [comment] 2019-06-09 19:10
It works on your site perfectly. 👍🏽
http://www.cryptoconsultant-blog.com

**Comment by pacollins** [comment] 2019-06-09 19:49
Are you using the current version of the theme? All of your content is
larger and the seems to be causing the issue.

Try removing all custom css and clearing your cache.

**Comment by Jonasdero** [comment] 2019-06-10 17:28
Thanks it is because of my font-size which I removed but somehow was still in the cache.

Is there a possibility to increase the font size without destroying the whole site?

**Comment by pacollins** [comment] 2019-06-10 23:22
```
html {
    font-size: #em //This is the default unit. Works in my site when adjusting via Chrome Dev tools.
} 
```

The issue is the different parameters that are set to ```px``` like the flyout menus. If you want to experiment, feel free and if you find something that seems to work, I can adjust the scss (or if you want to make a PR).

Can I ask why you want the font larger throughout? Most of the base sizes are from HTML5 Boilerplate or Normalize.css.
I'm closing since the bug is null. Feel free to keep commenting though.

**Closed by pacollins** 2019-06-10 23:22 UTC
Labels: Status: Available, Type: Bug

**Comment by weltruf** [comment] 2020-06-11 08:55
i have the same issue. When viewed on mobile device then i see just part of the side or have to zoom out. I even returned back to the original config.tofl but it did not help. Seems to have something to do with the blogpost content itself. You can see this site of another guy who obviously has the same problem but seems not to have noticed it yet: https://jhonmanuncia.me/blog/
